all:
	g++ -o E4 E4.cpp
	#g++ -o E4_fallido E4_fallido.cpp
	g++ -o E5 E5.cpp
	g++ -o E6 E6.cpp
	g++ -o E7 E7.cpp
	g++ -o E8 E8.cpp
	g++ -o E9_Structured E9_Structured.cpp
	g++ -o E9_Functional E9_Functional.cpp
	g++ -o E10 E10.cpp

clean:
	rm E4
	rm E5
	rm E6
	rm E7
	rm E8
	rm E9_Structured
	rm E9_Functional
	rm E10
